// Kontract Demo — Backend routes
//
// In a real project these are auto-generated by the Kontract compiler
// from @backend decorators. This demo shows the generated output format.

import { HttpResp, perms } from 'kontract';
import type { Context } from 'kontract';

// ── Types ───────────────────────────────────────────────
interface Task {
  id: string;
  title: string;
  done: boolean;
  owner: string;
}

// ── In-memory store (replace with TableProxy + PostgreSQL) ──
const tasks = new Map<string, Task>();

// ── Route registry (compiler output) ────────────────────
interface RouteDef {
  handler: (ctx: Context, args: unknown[]) => Promise<unknown>;
  meta: { egroup: string; perm: number };
}

export const routes = new Map<string, RouteDef>();

// ── @backend({ egroup: 'api-v1', perm: perms.RW_ })
routes.set('createTask', {
  handler: async (ctx, args) => {
    const [title] = args as [string];
    const id = crypto.randomUUID();
    const task: Task = { id, title, done: false, owner: ctx.owner };
    tasks.set(id, task);
    return HttpResp.created(task);
  },
  meta: { egroup: 'api-v1', perm: perms.RW_ },
});

// ── @backend({ egroup: 'api-v1', perm: perms.R__ })
routes.set('getTask', {
  handler: async (_ctx, args) => {
    const [id] = args as [string];
    const task = tasks.get(id);
    if (!task) return HttpResp.ok(null);
    return HttpResp.ok(task);
  },
  meta: { egroup: 'api-v1', perm: perms.R__ },
});

// ── @backend({ egroup: 'api-v1', perm: perms.R__ })
routes.set('listTasks', {
  handler: async (ctx) => {
    const owned = [...tasks.values()].filter(t => t.owner === ctx.owner);
    return HttpResp.ok(owned);
  },
  meta: { egroup: 'api-v1', perm: perms.R__ },
});

// ── @backend({ egroup: 'api-v1', perm: perms.RW_ })
routes.set('toggleTask', {
  handler: async (_ctx, args) => {
    const [id] = args as [string];
    const task = tasks.get(id);
    if (!task) return HttpResp.ok(null);
    task.done = !task.done;
    return HttpResp.ok(task);
  },
  meta: { egroup: 'api-v1', perm: perms.RW_ },
});

// ── @backend({ egroup: 'admin', perm: perms.RWX })
routes.set('deleteTask', {
  handler: async (_ctx, args) => {
    const [id] = args as [string];
    tasks.delete(id);
    return HttpResp.noContent();
  },
  meta: { egroup: 'admin', perm: perms.RWX },
});
